// scripts/populate-jobs.js
// Script to populate the Firebase database with sample job listings

const { initializeApp, cert } = require('firebase-admin/app');
const { getFirestore } = require('firebase-admin/firestore');
require('dotenv').config();

// Initialize Firebase Admin
const serviceAccount = JSON.parse(
  process.env.FIREBASE_SERVICE_ACCOUNT_KEY
);

initializeApp({
  credential: cert(serviceAccount),
  databaseURL: `https://${process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID}.firebaseio.com`
});

const db = getFirestore();
const jobsCollection = db.collection('jobs');

// Sample job data with varied filter values
const sampleJobs = [
  {
    title: "Senior Software Engineer",
    position: "software_engineer",
    company: "TechGiant Inc.",
    country: "united_states",
    city: "san_francisco_ca",
    location: "San Francisco, CA",
    description: "We are looking for a Senior Software Engineer to join our team. You will be responsible for designing, developing, and maintaining high-performance applications.",
    salary: "150000-180000",
    salaryCurrency: "USD",
    payRange: "more_than_120000",
    type: "Full-time",
    category: "Technology",
    experienceLevel: "Senior",
    teamManagement: "Yes",
    leadershipExperience: "Yes",
    sector: "Technology",
    workOption: "Remote",
    education: ["Bachelor's", "Master's"],
    functionalArea: "Engineering",
    travel: "No",
    jobLanguages: ["English"],
    applyUrl: "https://techgiant.com/careers/senior-software-engineer",
    keywords: ["JavaScript", "React", "Node.js", "AWS", "Senior", "Software Engineer"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: "Junior Frontend Developer",
    position: "software_developer",
    company: "StartupBoost",
    country: "germany",
    city: "berlin_be",
    location: "Berlin, Germany",
    description: "Join our fast-growing startup as a Junior Frontend Developer. You will work on building beautiful user interfaces for our products.",
    salary: "45000-60000",
    salaryCurrency: "USD",
    payRange: "40000_60000",
    type: "Full-time",
    category: "Technology",
    experienceLevel: "Junior",
    teamManagement: "No",
    leadershipExperience: "No",
    sector: "Technology",
    workOption: "Hybrid",
    education: ["Bachelor's"],
    functionalArea: "Engineering",
    travel: "No",
    jobLanguages: ["English", "German"],
    applyUrl: "https://startupboost.com/careers/junior-frontend-developer",
    keywords: ["HTML", "CSS", "JavaScript", "React", "Junior", "Frontend"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: "Data Scientist",
    position: "data_scientist",
    company: "DataCorp",
    country: "united_states",
    city: "new_york_ny",
    location: "New York, NY",
    description: "DataCorp is seeking a Data Scientist to join our analytics team. You will analyze large datasets and build predictive models.",
    salary: "120000-140000",
    salaryCurrency: "USD",
    payRange: "101000_120000",
    type: "Full-time",
    category: "Data Science",
    experienceLevel: "Mid-level",
    teamManagement: "No",
    leadershipExperience: "No",
    sector: "Technology",
    workOption: "On-site",
    education: ["Master's", "PhD"],
    functionalArea: "Data Science",
    travel: "Occasional",
    jobLanguages: ["English"],
    applyUrl: "https://datacorp.com/careers/data-scientist",
    keywords: ["Python", "R", "Machine Learning", "Statistics", "Data Science"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: "DevOps Engineer",
    position: "software_engineer",
    company: "CloudSystems",
    country: "canada",
    city: "toronto",
    location: "Toronto, Canada",
    description: "CloudSystems is looking for a DevOps Engineer to help us build and maintain our cloud infrastructure.",
    salary: "90000-110000",
    salaryCurrency: "USD",
    payRange: "81000_100000",
    type: "Full-time",
    category: "Technology",
    experienceLevel: "Mid-level",
    teamManagement: "No",
    leadershipExperience: "No",
    sector: "Technology",
    workOption: "Remote",
    education: ["Bachelor's"],
    functionalArea: "Engineering",
    travel: "No",
    jobLanguages: ["English"],
    applyUrl: "https://cloudsystems.com/careers/devops-engineer",
    keywords: ["AWS", "Docker", "Kubernetes", "CI/CD", "DevOps"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: "UI/UX Designer",
    position: "designer",
    company: "CreativeMinds",
    country: "france",
    city: "paris",
    location: "Paris, France",
    description: "Join our design team as a UI/UX Designer. You will create beautiful and intuitive user interfaces for our products.",
    salary: "70000-85000",
    salaryCurrency: "USD",
    payRange: "61000_80000",
    type: "Full-time",
    category: "Design",
    experienceLevel: "Mid-level",
    teamManagement: "No",
    leadershipExperience: "No",
    sector: "Creative",
    workOption: "Hybrid",
    education: ["Bachelor's"],
    functionalArea: "Design",
    travel: "No",
    jobLanguages: ["English", "French"],
    applyUrl: "https://creativeminds.com/careers/ui-ux-designer",
    keywords: ["UI", "UX", "Figma", "Adobe XD", "Design Systems"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: "Product Manager",
    position: "product_manager",
    company: "ProductFirst",
    country: "united_states",
    city: "austin_tx",
    location: "Austin, TX",
    description: "ProductFirst is seeking a Product Manager to lead our product development efforts. You will work closely with engineering, design, and marketing teams.",
    salary: "130000-150000",
    salaryCurrency: "USD",
    payRange: "101000_120000",
    type: "Full-time",
    category: "Product",
    experienceLevel: "Senior",
    teamManagement: "Yes",
    leadershipExperience: "Yes",
    sector: "Technology",
    workOption: "Hybrid",
    education: ["Bachelor's", "MBA"],
    functionalArea: "Product Management",
    travel: "Occasional",
    jobLanguages: ["English"],
    applyUrl: "https://productfirst.com/careers/product-manager",
    keywords: ["Product Management", "Agile", "Scrum", "Roadmap", "Strategy"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: "Marketing Specialist",
    position: "marketing_specialist",
    company: "GrowthHackers",
    country: "united_states",
    city: "miami_fl",
    location: "Miami, FL",
    description: "GrowthHackers is looking for a Marketing Specialist to help us grow our user base. You will be responsible for creating and executing marketing campaigns.",
    salary: "55000-70000",
    salaryCurrency: "USD",
    payRange: "61000_80000",
    type: "Full-time",
    category: "Marketing",
    experienceLevel: "Junior",
    teamManagement: "No",
    leadershipExperience: "No",
    sector: "Marketing",
    workOption: "On-site",
    education: ["Bachelor's"],
    functionalArea: "Marketing",
    travel: "No",
    jobLanguages: ["English", "Spanish"],
    applyUrl: "https://growthhackers.com/careers/marketing-specialist",
    keywords: ["Digital Marketing", "Social Media", "SEO", "Content Marketing"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: "Mechanical Engineer",
    position: "mechanical_engineer",
    company: "InnovateEngineering",
    country: "germany",
    city: "munich",
    location: "Munich, Germany",
    description: "InnovateEngineering is seeking a Mechanical Engineer to join our R&D team. You will design and develop mechanical components for our products.",
    salary: "75000-90000",
    salaryCurrency: "USD",
    payRange: "81000_100000",
    type: "Full-time",
    category: "Engineering",
    experienceLevel: "Mid-level",
    teamManagement: "No",
    leadershipExperience: "No",
    sector: "Manufacturing",
    workOption: "On-site",
    education: ["Bachelor's", "Master's"],
    functionalArea: "Engineering",
    travel: "Occasional",
    jobLanguages: ["English", "German"],
    applyUrl: "https://innovateengineering.com/careers/mechanical-engineer",
    keywords: ["CAD", "Mechanical Design", "Product Development", "Engineering"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: "Sales Representative",
    position: "sales_representative",
    company: "SalesForce",
    country: "united_states",
    city: "chicago_il",
    location: "Chicago, IL",
    description: "SalesForce is looking for a Sales Representative to join our team. You will be responsible for generating leads and closing deals.",
    salary: "50000-70000",
    salaryCurrency: "USD",
    payRange: "61000_80000",
    type: "Full-time",
    category: "Sales",
    experienceLevel: "Junior",
    teamManagement: "No",
    leadershipExperience: "No",
    sector: "Sales",
    workOption: "Hybrid",
    education: ["Bachelor's"],
    functionalArea: "Sales",
    travel: "Frequent",
    jobLanguages: ["English"],
    applyUrl: "https://salesforce.com/careers/sales-representative",
    keywords: ["Sales", "B2B", "Lead Generation", "CRM", "Negotiation"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: "Project Manager",
    position: "project_manager",
    company: "GlobalProjects",
    country: "canada",
    city: "vancouver",
    location: "Vancouver, Canada",
    description: "GlobalProjects is seeking a Project Manager to oversee our client projects. You will be responsible for planning, executing, and closing projects.",
    salary: "95000-115000",
    salaryCurrency: "USD",
    payRange: "81000_100000",
    type: "Full-time",
    category: "Project Management",
    experienceLevel: "Senior",
    teamManagement: "Yes",
    leadershipExperience: "Yes",
    sector: "Consulting",
    workOption: "Hybrid",
    education: ["Bachelor's", "PMP"],
    functionalArea: "Project Management",
    travel: "Occasional",
    jobLanguages: ["English"],
    applyUrl: "https://globalprojects.com/careers/project-manager",
    keywords: ["Project Management", "Agile", "Scrum", "PMP", "Leadership"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: "Mobile App Developer",
    position: "software_developer",
    company: "AppWorks",
    country: "united_states",
    city: "seattle_wa",
    location: "Seattle, WA",
    description: "AppWorks is looking for a Mobile App Developer to join our team. You will be responsible for developing and maintaining mobile applications for iOS and Android.",
    salary: "100000-120000",
    salaryCurrency: "USD",
    payRange: "101000_120000",
    type: "Full-time",
    category: "Technology",
    experienceLevel: "Mid-level",
    teamManagement: "No",
    leadershipExperience: "No",
    sector: "Technology",
    workOption: "Remote",
    education: ["Bachelor's"],
    functionalArea: "Engineering",
    travel: "No",
    jobLanguages: ["English"],
    applyUrl: "https://appworks.com/careers/mobile-app-developer",
    keywords: ["iOS", "Android", "Swift", "Kotlin", "React Native", "Mobile"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: "HR Manager",
    position: "hr_manager",
    company: "PeopleFirst",
    country: "france",
    city: "lyon",
    location: "Lyon, France",
    description: "PeopleFirst is seeking an HR Manager to oversee our human resources department. You will be responsible for recruiting, onboarding, and employee relations.",
    salary: "85000-100000",
    salaryCurrency: "USD",
    payRange: "81000_100000",
    type: "Full-time",
    category: "Human Resources",
    experienceLevel: "Senior",
    teamManagement: "Yes",
    leadershipExperience: "Yes",
    sector: "Human Resources",
    workOption: "On-site",
    education: ["Bachelor's", "Master's"],
    functionalArea: "Human Resources",
    travel: "No",
    jobLanguages: ["English", "French"],
    applyUrl: "https://peoplefirst.com/careers/hr-manager",
    keywords: ["HR", "Recruiting", "Employee Relations", "Benefits", "Compensation"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: "Content Writer",
    position: "content_writer",
    company: "ContentKing",
    country: "united_kingdom",
    city: "london",
    location: "London, UK",
    description: "ContentKing is looking for a Content Writer to create engaging content for our blog and social media channels. You will be responsible for researching, writing, and editing content.",
    salary: "40000-55000",
    salaryCurrency: "USD",
    payRange: "40000_60000",
    type: "Full-time",
    category: "Content",
    experienceLevel: "Junior",
    teamManagement: "No",
    leadershipExperience: "No",
    sector: "Media",
    workOption: "Remote",
    education: ["Bachelor's"],
    functionalArea: "Content",
    travel: "No",
    jobLanguages: ["English"],
    applyUrl: "https://contentking.com/careers/content-writer",
    keywords: ["Content Writing", "SEO", "Blogging", "Copywriting", "Editing"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: "Financial Analyst",
    position: "financial_analyst",
    company: "FinanceWise",
    country: "united_states",
    city: "boston_ma",
    location: "Boston, MA",
    description: "FinanceWise is seeking a Financial Analyst to join our team. You will be responsible for analyzing financial data and creating financial models.",
    salary: "75000-90000",
    salaryCurrency: "USD",
    payRange: "81000_100000",
    type: "Full-time",
    category: "Finance",
    experienceLevel: "Mid-level",
    teamManagement: "No",
    leadershipExperience: "No",
    sector: "Finance",
    workOption: "Hybrid",
    education: ["Bachelor's", "CFA"],
    functionalArea: "Finance",
    travel: "No",
    jobLanguages: ["English"],
    applyUrl: "https://financewise.com/careers/financial-analyst",
    keywords: ["Financial Analysis", "Excel", "Financial Modeling", "Forecasting"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: "Customer Support Specialist",
    position: "customer_support",
    company: "SupportHero",
    country: "canada",
    city: "montreal",
    location: "Montreal, Canada",
    description: "SupportHero is looking for a Customer Support Specialist to help our customers resolve issues. You will be responsible for answering customer inquiries and troubleshooting problems.",
    salary: "45000-55000",
    salaryCurrency: "USD",
    payRange: "40000_60000",
    type: "Full-time",
    category: "Customer Support",
    experienceLevel: "Junior",
    teamManagement: "No",
    leadershipExperience: "No",
    sector: "Customer Service",
    workOption: "Remote",
    education: ["High School", "Bachelor's"],
    functionalArea: "Customer Support",
    travel: "No",
    jobLanguages: ["English", "French"],
    applyUrl: "https://supporthero.com/careers/customer-support-specialist",
    keywords: ["Customer Support", "Troubleshooting", "Communication", "Problem Solving"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: "Graphic Designer",
    position: "graphic_designer",
    company: "DesignStudio",
    country: "germany",
    city: "hamburg",
    location: "Hamburg, Germany",
    description: "DesignStudio is seeking a Graphic Designer to join our creative team. You will be responsible for creating visual concepts and designs for our clients.",
    salary: "60000-75000",
    salaryCurrency: "USD",
    payRange: "61000_80000",
    type: "Full-time",
    category: "Design",
    experienceLevel: "Mid-level",
    teamManagement: "No",
    leadershipExperience: "No",
    sector: "Creative",
    workOption: "On-site",
    education: ["Bachelor's"],
    functionalArea: "Design",
    travel: "No",
    jobLanguages: ["English", "German"],
    applyUrl: "https://designstudio.com/careers/graphic-designer",
    keywords: ["Graphic Design", "Adobe Creative Suite", "Typography", "Branding"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];

// Function to add jobs to the database
async function addJobsToDatabase() {
  console.log('Starting to add jobs to the database...');
  
  try {
    // Add each job to the database
    for (const job of sampleJobs) {
      await jobsCollection.add(job);
      console.log(`Added job: ${job.title}`);
    }
    
    console.log('Successfully added all jobs to the database!');
  } catch (error) {
    console.error('Error adding jobs to the database:', error);
  }
}

// Run the function
addJobsToDatabase();
